name: Run example

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  app-jobs:
    # needs: setup
    # services:
    #   anoma:
    #     image: m1dnight/anoma:latest
    #     ports:
    #       - 4000:4000
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [Spacebucks]
      fail-fast: false  # Allows other jobs to continue even if one fails
      max-parallel: 5  # Run all 5 jobs concurrently
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.3.3
          elixir-version: 1.18.3
      - name: Checkout code
        uses: actions/checkout@v4

      - name: download juvix compiler
        run: |
          DOWNLOAD_URL="https://github.com/anoma/juvix-nightly-builds/releases/download/nightly-2025-05-20-0.6.10-6acdc3a/juvix-linux-x86_64.tar.gz"
          curl -L -o juvix.tar.gz "$DOWNLOAD_URL"
          tar -xzf juvix.tar.gz
          chmod +x juvix

          # Verify the download
          ./juvix --version

          # Move to a location in PATH
          mkdir -p $HOME/.local/bin
          mv juvix $HOME/.local/bin/
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run ${{ matrix.app }}
        run: |
          echo "Running ${{ matrix.app }}"

          # create output directory if it doesn't exist
          mkdir -p ${{matrix.app}}/.compiled

          # compile all juvix files
          for file in $(find ${{matrix.app}} -type f -name "*.juvix"); do
            filename=$(basename "$file")
            echo "Compiling $file to .compiled/${filename%.juvix}.nockma"
            juvix compile anoma "$file" -o "${{matrix.app}}/.compiled/${filename%.juvix}.nockma"
          done

          elixir ${{matrix.app}}/run.exs
